version: "3.5"

services:
  grafana8:
    image: grafana/grafana:latest
    network_mode: "bridge"
    container_name: grafana8
	
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    
    ##run # id -u 1001 && sudo chown 472:472 data/
